all:
  children:
    wsl:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become: false

    rpi:
      hosts:
        rpi5b:
          ansible_host: 192.168.88.10
          ansible_user: root
        # tinkerboard:
        #   ansible_host: 192.168.88.XX
        #   ansible_user: root
